### ISSUE TITLE
Nachrichten: Effekt-Zeit und Flags

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#10]
Ich versuche gerade zu testen, ob das "Börsennews"-Cleanup funktioniert - tut es natürlich nicht.
Ziel: einmal unsichtbare Initial-Trigger-Nachrichten (Typ 0), selbst-anstoßende Folgenachrichen (Typ 2)
Warum: weil meiner Ansicht nach nur Nachfolgenachrichten angestoßen werden sollten (Vermeiden von Dopplern durch Anstoßen und Auswahl als Initialnachrichten)

Ich bekomme allerdings nicht hin, dass Nachfolgekette nicht bricht. Testweise wollte ich die Börsennachrichten alle 1-2 Stunden senden. Das klappt einige Male, dann kommen aber gar keine mehr - auch wenn ich die Nachricht auf nicht skippable setze und der Effekt eintritt auch wenn die Nachricht nicht gesendet wird.

Möglicherweise ist das Problem, dass der Trigger zwar definitiv feuert, die Nachricht dann aber nicht in die Auswahl kommt und damit auch der nächste Trigger nicht mehr existiert. Ich habe noch nicht probiert, ob sendImmediately hilft (aber das könnte auch bedeuten ohne Verzögerung, aber nur, wenn überhaupt ausgewählt).

Ggf. sind regelmäßige Nachrichten gar nicht wirklich im Konzept, aber in diesem Fall sollten die Börsennachrichen sich auch nicht selbst triggern. Sauberer wären sie dann als Initialnachrichten, die an Wochentagen verfügbar sind (über availability?).

**Comment by nittka** [comment]
Vielleicht kannst Du nochmal schauen, ob es ein Problem im Code ist oder ob meine Konfigurationsidee so nicht funktionieren kann. Meine Erwartung ist, dass ein News-Effekt mit Wahrscheinlichkeit 100 auch definitiv stattfindet. Wenn eine Nachfolgenachricht angestoßen wird, muss sie auch verfügbar sein. Lediglich neue Startnachrichten sollten zurückgehalten werden.

**Comment by GWRon** [comment]
Wieso muss seine Nachricht automatisch verfuegbar sein?

Wenn eine Nachricht eine andere zu 100% ausloest, ist das ein "wollen". 
Die ausgeloeste Nachricht kann ja bspweise nur in den 90ern verfuegbar sein. Eine zweite ausgeloeste Nachricht nur in den 0ern.
Beide sollen aber zu 100% ausgeloest werden..also kaeme es in 1990-2009 auf alle Faelle zu der Folgenachricht.

**Comment by nittka** [comment]
Wenn es aber keine Einschränkung der Verfügbarkeit für die Nachfolgenachricht gibt, warum wird sie dann bei 100% Wahrscheinlichkeit nicht immer angeboten.
Wie gesagt, Ausgangspunkt sind die Börsennachrichten, die sich selbst triggern. Wenn die Kette einmal unterbrochen ist, kommen sie potentiell nie wieder (nach dem Refactoring). Ansonsten sehe ich für sie überhaupt keinen Grund, sich selbst zu triggern. Sie könnten einfach per Verfügbarkeit immer wieder als Initialnachricht gesendet werden. Die Idee hinter dem Trigger ist ja wahrscheinlich, dass sie regelmäßig an Arbeitstagen gesendet werden können. Das geht aber schief, wenn man sich nicht auf den Trigger verlassen kann.

Im Test habe ich sie sich alle 1-2 Stunden triggern lassen. Das geht 4 bis 5 mal gut. Danach kommt die Nachricht nie wieder.

**Comment by nittka** [comment]
... Ich habe die Effekt-Zeit wie happenTime bei einer Initialnachricht interpretiert. Dort hast Du den Unterschied mit happenTime (muss) und availability (kann) herausgestellt; und ich finde es sinnvoll, dass eine solche Unterscheidung möglich ist. Wenn die aktuelle Implementierung diesen Unterschied für Nachfolgenachrichten(!) nicht vorsieht (und auch das unskippable-Flag dafür nicht geeignet ist), kann ggf. ein neues Flag `useEffectTimeAsHappenTime` für Nachfolgenachrichten eingeführt werden.

**Comment by GWRon** [comment]
Ging es denn vor dem Refactoring fehlerfrei durch?

Wenn nicht, kann ich da schauen, woran es liegt...

**Comment by nittka** [comment]
Das ist halt schwer zu sagen. Im aktuellen Datenbankstand ist die Börsennachricht ja vom Typ 0, steht also prinzipiell wieder als Initialnachricht zur Verfügung, hat initial eine happenTime, die aber per Flag zurückgesetzt wird und sie triggert sich selbst (aber nur arbeitstäglich), so dass es nicht so leicht ist, das über einen längeren Zeitraum zu beobachten.

Die Frage ist ja vorrangig: was ist das aktuell erwartete (implementierte) Verhalten bei Trigger mit Zeit und 100% Wahrscheinlichkeit. Wenn die Nachricht dann angeboten werden muss, stimmt etwas noch nicht (außer ich habe noch ein "keep/reset"-Flag vergessen zu setzen. Wenn sie nur angeboten werden *soll*, gibt es eine "Konzeptionslücke", da mit nicht erzwingen kann, dass die Nachricht angeboten wird (wenn unskippable+keep/reset nicht ausreichen).

**Comment by nittka** [comment]
Das Problem wurde mit den Fixes zur Zeitberechnung behoben.
