### ISSUE TITLE
Dokumentation DB-Editor

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#14]
Die erste vorzeigbare Version des Editors ist fertig. Ich habe noch kein Release gebaut, aber eine Eclipse-Snapshot-Update-Site auf meine Homepage gepackt (https://www.nittka.de/download/tvtdb).
Meine Überlegung ist, die Dokumentation für den Editor auch imDoku-Repo abzulegen.
* Readme im Editor-Repo reicht nicht aus
* Doku-Verzeichnis im Editor-Repo vermischt Commit-Historie zwischen Editor und Doku
Man könnte natürlich auch ein Editor-Wiki anfangen, aber ich, wie gesagt, mag ich das Github-Wiki wegen der fehlenden Möglichkeit zur ordentlichen Strukturierung nicht.

Hast Du dazu eine Meinung?

**Comment by GWRon** [comment]
Ich lass dir da relativ freie Wahl. Hab da an sich keine eigene Meinung dazu.

**Comment by nittka** [comment]
OK. Dann würde ich unter database_editor/xtext_de die Editor-Dokumentation anfangen.

**Comment by nittka** [comment]
Initiale Dokumentation erstellt in https://github.com/TVTower/Documentation/commit/8110d0dc63a3d73052528844550053c9f575262d
