### ISSUE TITLE
Review Konzept Live-Ausstrahlung/Limits etc

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#15]
In diesem Ticket und dem dazugehörigen Branch wird die aktuelle Umsetzung für Live-Übertragungen und verwandte Flags/Limits geprüft werden.
Am Ende der Diskussion steht dann ein Vorschlag für Implementierungsanpassungen.

Vorschlag für die Diskussion: Ich pflege das Hauptdokument ("Konzept") und in einem parallelen Dokument/als Kommentar direkt am Commit kann Rückmeldung gegeben werden, die ich dann einarbeite.

**Comment by nittka** [comment]
Feedback aus TVTower-Ticket wurde in eine separate Datei übernommen und beantwortet (https://github.com/TVTower/Documentation/tree/liveLimit/developer/concepts). Für zentrale Punkte wurde die Konzeptdatei entsprechend angepasst.

**Comment by nittka** [comment]
Ich wühle gerade etwas im Code bezüglich Live-Datum.
Im Gegensatz zum Drehbuch hat das Programm keinen separates Live-Datum mehr. Hier wird das Release-Datum verwendet, das für sämtliche Programme benötigt wird. Wenn man nun nicht Release-Datum und Live-Datum voneinander lösen möchte, kann das existierende AlwaysLive-Flag umgewidmet werden. Es würde aussagen, dass der Live-Zeitpunkt nicht festgelegt ist - AlwaysLive.
Ob man das Flag nach der ersten Ausstrahlung löscht oder bei der Live-Abfrage immer Flag und Ausstrahlungshäufigkeit auswertet, könnte davon abhängig gemacht werden, wie/wo die Abfrage erfolgt.

D.h. nicht Abschaffung des Flags, sondern Umwidmung. Für Drehbücher könnte man das Flag implizit setzen, wenn kein Live-Date angegeben ist.

**Comment by nittka** [comment]
Ich habe das Dokument überarbeitet. Interessant dürfte sein, ob ich bei der expliziten Aufzählung der "Klassen von Anwendungsfällen" was vergessen habe.
Bei meinem Umsetzungsprototypen ist mir aufgefallen, dass auch das "Slot berücksichtigen"-Flag entfallen kann. Da die Slot-Definition nicht mehr für die Live-Zeit-Berechnung verwendet wird, muss nicht explizit gesagt werden, dass die Slots berücksichtigt werden sollen (warum sonst gibt man sie an).

**Comment by nittka** [comment]
Ich habe im Konzept leider einen kapitalen Denkfehler bei den als live markierten Programmen...
Man kann zwar mit Ausstrahlungslimit und Auto-Remove die Rückgabe eines Nicht-mehr-live-Programms erreichen. Dadurch wird aber das Live-Flag nicht wieder gesetzt.
Möglicherweise lässt sich das reparieren, indem man die Ausstrahlungshäufigkeit in die isLive-Berechnung eingehen lässt.

**Comment by GWRon** [comment]
Der Liveflag laesst sich bei Rueckgabe ja keicht wieder setzen...
Allerdings muss dafuer bekannt sein, dass es vorher mal live war (was liveOnTape nicht unbedingt bedingen muss...man koennte ja ein livekonzert "on tape" als Lizenz anbieten).
Evtl also einen weiteren Flag definieren..der bei Rueckgabe den Liveflag setzt. Und der Flag wird bei Liveausstrahlung dann aktiviert.

**Comment by nittka** [comment]
Ich glaube, es könnte auch funktionieren, die Flags nach einer Ausstrahlung gar nicht umzusetzen, sondern bei isLive/isLiveOnTape an der Lizenz die Ausstrahlungshäufigkeit zu berücksichtigen.
isLive= liveFlag und keine Ausstrahlung
isLiveOnTape = liveOnTapeFlag oder liveFlag und mindestens 1 Ausstrahlung

**Comment by GWRon** [comment]
Ja das koennte gehen, da ja kein AlwaysLive-Flag mehr existiert.

**Comment by nittka** [comment]
Die Umsetzung ist erfolgt. Ich habe Konzeptnotizen in die Dokumentation übernommen.
