### ISSUE TITLE
price_mod bei Lizenzen

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#17]
Laut Wiki ist "price_mod" bei Lizenzen "outdated" und die modifier-tags können/sollten verwendet werden. In der Datenbank ist in database_programmes aber noch fast überall price_mod in Verwendung (455x). Sollten die umgestellt werden?

**Comment by GWRon** [comment]
Das kannst Du gerne machen. 

Und am Ende muesste man evtl noch die database bmx -Datei so anpassen, dass es "notify()" macht, wenn price_mod noch gefunden wird (custom db Nutzer). Also zumindest uebergangsmaessig.

**Comment by nittka** [comment]
Ich möchte hier keine Anpassung vornehmen. Selbst wenn man alle Einträge mit price_mod=1 löscht, bleiben sehr viele Anpassungen übrig. Und der syntaktische Mehraufwand für den einen Modifier ist sehr hoch.
Und im Wiki steht nichts mehr von "outdated" ist ja in die Dokumentation gewandert.
