### ISSUE TITLE
Verfügbarkeit von Programmen

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#5]
Siehe Diskussion https://github.com/TVTower/Documentation/commit/cc9d1cab0e961e10da42096aabbd8ee6743fcf2d#r50135747

Argumente hier konsolidieren und nach Klärung Ticket für die Umsetzung aufmachen.

**Comment by nittka** [comment]
Ich glaube, die gegenseitige Verwirrung in der Commit-Diskussion rührt daher, dass ich aus Sicht der Datenbank-Inhalte gespochen, es aber aus Sicht des Quellcodes interpretiert wurde.
In den XML-Dateien kommt Veröffentlichungsinformation im Programmdaten-Tag vor (year sowie year_relative mit min, max) sowie im ReleaseTime-Tag. Zusätzlich hatte ich beim Ersellen der Grammatik wohl einen Copy/Paste-Fehler gemacht und bei den Programmen auch hoch einen availability-Knoten erlaubt (der aber gar nicht in den Daten vorkommt) - die Diskussion, ob availability sinnvoll einsetzbar ist, würde ich deshalb einfach fallen lassen.

Beim Datenbankeinlesen werden year, relative etc. in ein ReleaseTime-Objekt eingelesen (wobei es hier noch deutlich mehr Attribute gibt, als in den Daten verwendet werden).

Wegen der absolut hohen Zahl von year-Einträgen im data-Tag, würde ich das Jahr dort lassen (das erlaubt auch kürzere Einträge, wenn einem nichts außer dem absoluten Jahr wichtig ist). Relative Jahre gibt es sehr wenige. Die würde ich beim Datenbankaufräumen in den releaseTime-Knoten verschieben.

Klingt das nach einem Plan?

**Comment by GWRon** [comment]
Zwecks "Verschiebung" - man muss ueberlegen, ob die XML-Dateien von Nutzern "gesehen" werden. Wenn da die Einhaengeknoten fuer "relative Veroeffentlichungszeitpunkte" und "absolutes Veroeffentlichungsjahr" unterschiedlich sind, ist das irgendwie "unschoen".

Arrangieren kann ich mich aber mit vielem, also soll das kein Hindernisgrund sein.

**Comment by nittka** [comment]
Der aktuelle Einlese-Code liest schon jetzt die gesamten releaseTime-Eigenschaften sowohl aus dem data-Knoten als auch aus dem releaseTime-Knoten. D.h. man könnte schon jetzt die Hälfte an der einen Stelle und die andere Hälfte an der anderen hinschreiben.
Für die Beschreibung der Datenbankstruktur hätte ich gern eine "klare Regelung" (eine Code-Anpassung wäre hier gar nicht nötig). Und im Normalfall wird man nur das absolute Jahr angeben. Dafür reicht "year" in "data" aus und man muss nicht extra einen releaseTime-Knoten anlegen (der kann ja year auch behalten).

So lange es keinen Nicht-Text-Editor für die Datenbank gibt, wird sich ein Bearbeiter die XML-Dateien anschauen müssen. Deshalb möchte ich ja auch die Dokumentation so aussagekräftig (und eindeutig) wie möglich und die Datenbankdateien in einem aufgeräumten Zustand haben. Neue Einträge werden oft auf copy/paste basieren. Da multiplizieren sich sowohl gute als auch schlechte Muster.

**Comment by nittka** [comment]
Ich habe die Dokumentation und die Datenbank entsprechend angepasst (im neuen Commit zum Aufräum-PR). Wenn das so OK ist, mache ich dieses Ticket zu.
