### ISSUE TITLE
Bedeutung rt_id (in Programmen)

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#7]
Im Programm-Hauptknoten kommt sehr oft die Eigenschaft rt_id vor. In fast allen Fällen ist der Wert "0". In einer Hand von Fällen ist er 8751 mit creator="TheRob" (hier vermute ich copy-Paste-Fehler creator="8751" createdBy="TheRob"), einmal enthält er eine imdb-ID.

Spricht etwas dagegen, die wenigen Einträge zu korrigieren und die rt_id komplett zu entfernen; beim Datenbankeinlesen scheint das auch keine Rolle zu spielen?

**Comment by GWRon** [comment]
ahh ... ich glaube "rt_id" war als "rotten tomatoes"-ID angedacht - hat nur nie jemand ausgefuellt.

Kann da wohl dann "weg"

**Comment by GWRon** [comment]
Sinn der IMDB/TMDB... IDs war/ist, automatisiert Daten "nachholen" zu koennen (bspweise Filmposter fuer TV, Schauspielernamen, aktuelle Userwertungen .. um diese In Attribute umzurechnen etc)

**Comment by nittka** [comment]
OK. Dann werfe ich das raus.

**Comment by nittka** [comment]
In Editor und Datenbank-Cleanup entfernt.
