### ISSUE TITLE
ID von Rollen

### ISSUE THREAD

**Issue by nittka** [TVTower/Documentation#8]
In der Datenbank gibt es Rollen mit guid und id, beim Einlesen der Datenbank wird aber scheinbar nur guid ausgewertet. Soll hier id konsistent nach guid umbenannt werden?

**Comment by GWRon** [comment]
Ja, in der DB nur "GUID" (vielleicht wollte bei ID jemand die IMDB-ID angeben? glaube fuer einige "rollen" gibt es da was).

die GUID = in der XML (und auch im Spiel) genutzter Identifikationsschluessel. "ID" ist im Spiel ein numerischer Wert, der nur fuer diese explizite Spielsession genutzt wird (aber ein performanteres Abfragen erlaubt - da halt nur Nummern verglichen werden, statt 40-Zeichen lange Strings)

**Comment by nittka** [comment]
role id wird durch role guid ersetzt.
